// <auto-generated />
using System;
using Airlineservice.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Airlineservice.Migrations
{
    [DbContext(typeof(AirlineContext))]
    [Migration("20220427091505_DiscountCoupon_tableCreated")]
    partial class DiscountCoupon_tableCreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Airlineservice.Models.BookFlight", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiscountCouponID")
                        .HasColumnType("int");

                    b.Property<int>("FinalPrice")
                        .HasColumnType("int");

                    b.Property<int>("FlightID")
                        .HasColumnType("int");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightSeatNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FlightStartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FlightToDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromPlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Meal")
                        .HasColumnType("int");

                    b.Property<int>("No_of_Seats")
                        .HasColumnType("int");

                    b.Property<long>("PNR")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TicketCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ToPlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingId");

                    b.ToTable("bookFlights");
                });

            modelBuilder.Entity("Airlineservice.Models.DiscountCoupon", b =>
                {
                    b.Property<int>("DiscountCouponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CouponCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("couponvalue")
                        .HasColumnType("int");

                    b.HasKey("DiscountCouponID");

                    b.ToTable("DiscountCoupons");
                });

            modelBuilder.Entity("Airlineservice.Models.FlightDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Airline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightSeatRow")
                        .HasColumnType("int");

                    b.Property<DateTime>("FlightStartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FlightToDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromPlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Meal")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ToPlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBusinessSeats")
                        .HasColumnType("int");

                    b.Property<int>("TotalNonBusinessSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FlightDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
